# Generated by Django 5.1.4 on 2025-01-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
